version: "3"
services:
  vpn_gateway_openvpn:
    image: docker.io/kylemanna/openvpn
    container_name: vpn_gateway_openvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    environment:
      DNS_PRIMARY: ${DNS_PRIMARY:-1.1.1.1}
      DNS_SECONDARY: ${DNS_SECONDARY:-1.0.0.1}
    volumes:
      - ./config/auth.txt:/vpn_config/auth.txt:Z,ro
      - ./config/${VPN_CONFIG_FILE_NAME:-vpn.ovpn}:/vpn_config/vpn.ovpn:Z,ro
      - ./scripts/start-openvpn.sh:/scripts/start-openvpn.sh:Z,ro
    ports:
      - "${SOCKS_BIND_HOST:-127.0.0.1}:${SOCKS_BIND_PORT:-1080}:1080"
    command: ["/scripts/start-openvpn.sh"]

  vpn_gateway_socksproxy:
    image: docker.io/wernight/dante
    container_name: vpn_gateway_socksproxy
    network_mode: "container:vpn_gateway_openvpn"
    depends_on:
      - vpn_gateway_openvpn
    volumes:
      - ./config/danted.conf:/etc/sockd.conf:Z,ro
      - ./scripts/start-dante.sh:/scripts/start-dante.sh:Z,ro
    command: ["/scripts/start-dante.sh"]
